# Generated by Django 3.1.7 on 2021-03-19 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='', max_length=100)),
                ('task_finshed', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, default='', max_length=100)),
                ('category', models.CharField(blank=True, choices=[('programming', 'Programming'), ('bugfixing', 'Bugfixing'), ('something', 'Something')], max_length=120)),
                ('finshed', models.DateTimeField(blank=True, null=True)),
                ('assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_user', to=settings.AUTH_USER_MODEL)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
