# Generated by Django 3.1.7 on 2021-03-22 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='finshed',
            new_name='finished',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_finshed',
            new_name='task_finished',
        ),
    ]
