# Generated by Django 3.1.7 on 2021-03-23 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20210323_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_user',
            new_name='creator',
        ),
    ]
