# Generated by Django 3.1.7 on 2021-03-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20210323_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
