# Generated by Django 3.1.7 on 2021-03-24 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_task_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='finished',
        ),
    ]
